CREATE TABLE pages(
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    uri_slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL
);
--;;
CREATE TABLE revisions(
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    page_id INTEGER NOT NULL REFERENCES pages(id),
    body TEXT
);
